package sk.uniza.fri.inf.gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 * 6. 5. 2022 - 9:58
 *
 * @author Michal
 */
public class HlavneOkno {
    private JList<Student> listStudentov;
    private JPanel panel1;
    private JButton pridajButton;
    private JButton upravButton;
    private JButton zmazButton;

    public HlavneOkno() {
        DefaultListModel<Student> model = new DefaultListModel<>();
        listStudentov.setModel(model);
        model.addElement(new Student("Janko", "Hrasko", 19));
        model.addElement(new Student("Jurko", "Mrkvicka", 19));
        model.addElement(new Student("Jurko", "Mrkvicka", 19));
        model.addElement(new Student("Jurko", "Mrkvicka", 19));
        model.addElement(new Student("Jurko", "Mrkvicka", 19));
        model.addElement(new Student("Jurko", "Mrkvicka", 19));
        model.addElement(new Student("Jurko", "Mrkvicka", 19));

        listStudentov.setCellRenderer(new ListCellRenderer<Student>() {
            private JLabel label = new JLabel();

            @Override
            public Component getListCellRendererComponent(JList<? extends Student> list, Student value, int index, boolean isSelected, boolean cellHasFocus) {
                label.setText(index + ". " + value.meno() + " " + value.priezvisko() + " (" + value.vek() + ")");
                if (isSelected) {
                    label.setForeground(Color.red);
                    label.setBackground(Color.green);
                } else {
                    label.setForeground(Color.black);
                    label.setBackground(list.getBackground());
                }
                return label;
            }
        });

        JFrame jFrame = new JFrame("Zoznam studentov");
        jFrame.setContentPane(panel1);
        jFrame.setLocationRelativeTo(null);
        jFrame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        jFrame.pack();
        jFrame.setVisible(true);
        zmazButton.addActionListener(e -> {
            int volba = JOptionPane.showConfirmDialog(jFrame, "Skutocne chcete zmazat studenta/ov", "Zmazať", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (volba == JOptionPane.YES_OPTION) {
                List<Student> students = listStudentov.getSelectedValuesList();
                for (Student student : students) {
                    model.removeElement(student);
                }
            }
        });

        pridajButton.addActionListener(e -> {
            StudentDialog dialog = new StudentDialog();
            dialog.setTitle("Pridanie studenta");
            dialog.setLocationRelativeTo(panel1);
            dialog.pack();
            dialog.setVisible(true);

            if (dialog.getStudent() != null) {
                model.addElement(dialog.getStudent());
            }
        });


        upravButton.addActionListener(e -> {
            Student student = listStudentov.getSelectedValue();
            if (student == null) return;

            StudentDialog dialog = new StudentDialog(student);
            dialog.setTitle("Pridanie studenta");
            dialog.setLocationRelativeTo(panel1);
            dialog.pack();
            dialog.setVisible(true);

            if (dialog.getStudent() != null) {
                model.removeElement(student);
                model.addElement(dialog.getStudent());
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        listStudentov = new JList();
        listStudentov.setMinimumSize(new Dimension(300, 150));
        listStudentov.setPreferredSize(new Dimension(300, 200));
        panel1.add(listStudentov, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel2.setPreferredSize(new Dimension(120, 56));
        panel1.add(panel2, BorderLayout.EAST);
        pridajButton = new JButton();
        pridajButton.setText("Pridaj");
        panel2.add(pridajButton);
        upravButton = new JButton();
        upravButton.setText("Uprav");
        panel2.add(upravButton);
        zmazButton = new JButton();
        zmazButton.setHorizontalAlignment(0);
        zmazButton.setText("Zmaž");
        panel2.add(zmazButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
